name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "nakashima-masaya"
          # ICON_FIRST: "#3657a6"
          # ICON_SECOND: "#00aaff"
          # BACKGROUND_FIRST: "#020e27"
          # BACKGROUND_SECOND: "#0e5593"
          # LANG: "en"
