name: qiita feed gate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  qiita-feed:
    name: Qiita feed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://qiita.com/kawa18/feed'
          file: 'README.md'
